name: hello-world
on: push¨
name: JAVA CI
jobs:
runs-on: ubuntu-latest
container: gradle:6-jdk11
  Clone-down:
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - run: ci/build-app.sh
  Build:
    steps:
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .