name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2

      - run: ci/build-app.sh

      - name: Test
        run: ci/unit-test-app.sh

        - name: Download a single artifact
          uses: actions/download-artifact@v2
          with:
            name: my-artifact
            path: path/to/download/artifact/

      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
